spring.application.name=basiAuth

spring.datasource.url = jdbc:postgresql://localhost:5432/basicAuthNTO
spring.datasource.username = postgres
spring.datasource.password = timn2020
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

spring-doc.swagger-ui.path = /docs